### ISSUE TITLE
[BUG][0.4.0] lunch problems

### ISSUE THREAD

**Issue by FPSensor** [Vankata453/supertux-launcher#2]
- OS: Windows 10
 - Installed SuperTux versions: 0.4.0

Wen u try to open SuperTux 0.4.0 it fails showing this msg

![image](https://user-images.githubusercontent.com/112205924/209507258-2abf9a4d-77ba-4ea2-9e6c-6b6aa1826abe.png)

**Steps to reproduce the behavior:**
1: install SuperTux 0.4.0
2: try to run it

**Comment by FPSensor** [comment]
well so i edited it cuz i get to run ST063 after delete all installed supertux and try again but now have this problem with 040

**Comment by provigz** [comment]
1. Try to play the release again.
2. After you get the error message, go to `%appdata%/SuperTux/supertux` and send the `console.out` and `console.err` files.

**Comment by FPSensor** [comment]
there is not supertux folder

**Comment by provigz** [comment]
Try to open the release's "Installation directory" from the dropdown menu next to the "Play!" button, and afterwards go into the `bin` folder and try to launch `supertux2.exe`.

**Comment by FPSensor** [comment]
ok i tried and missing some dll
![image](https://user-images.githubusercontent.com/112205924/213525576-96ff81ab-8a0b-4a72-baca-4d9393b71fae.png)
![image](https://user-images.githubusercontent.com/112205924/213525630-f7b08eea-7a81-420e-b56a-46f0e400ea44.png)
![image](https://user-images.githubusercontent.com/112205924/213525660-4b31804f-a090-4b6c-937e-49f6e133c708.png)
![image](https://user-images.githubusercontent.com/112205924/213525680-3ab8010f-726b-48f0-bf7d-84b36b37d3dc.png)


also i installed Visual C++ to see if fixes and still not working

**Comment by provigz** [comment]
This is an issue with missing DLLs and is not related to the functionality of the launcher. I would suggest attempting to install [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

**Comment by FPSensor** [comment]
installed and not worked lol
but anyway true not launcher problem
